version: '3.7'

services:
  consul:
    image: consul:latest
    ports:
      - "18400:8400"
      - "18500:8500"
      - "18600:8600"
      - "18600:8600/udp"
    command: "agent -server -bootstrap-expect 1 -ui -client 0.0.0.0"
    networks:
      - surging_demo_service_net
  redis:
    image: redis:latest
    ports:
      - "16379:6379"
    networks:
      - surging_demo_service_net
  rabbitmq:
    image: rabbitmq:management
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "15673:15672"
      - "5673:5672"
    networks:
      - surging_demo_service_net
  mysql:
    image: mysql:8.0.15
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "qwe!P4ss"
      MYSQL_USER: "hl"
      MYSQL_PASSWORD: "qwe!P4ss"
    volumes:
      - ./.mysql/data:/var/lib/mysql
    ports:
      - "23306:3306"
    networks:
      - surging_demo_service_net
networks:
  surging_demo_service_net: 
    driver: bridge
    name: hl_surging_service_net
    ipam:
      driver: default
      config:
      - subnet: 172.21.0.1/16
