version: '3.7'

services: 
  hlservice.basicdata:
    image: hlservice/basicdata:${TAG:-latest}
    build:
      context: ../..
      dockerfile: src/Servers/BasicData/Hl.BasicData.ServerHost/Dockerfile
      args:
        host_workdir: src/Servers/BasicData/Hl.BasicData.ServerHost
        host_name: Hl.BasicData.ServerHost.dll
        sln_name: sln/Surging.HlWithIdentity.sln
    volumes:
      - ${LOG_DIR:-/var/logs}/basicdata:/app/logs
    networks:
      - src_srcp_demo_service_net

  hlservice.identity:
    image: hlservice/identity:${TAG:-latest}
    build:
      context: ../..
      dockerfile: src/Servers/Identity/Hl.Identity.ServerHost/Dockerfile
      args:
        host_workdir: src/Servers/Identity/Hl.Identity.ServerHost
        host_name: Hl.Identity.ServerHost.dll
        sln_name: sln/Surging.HlWithIdentity.sln
    volumes:
      - ${LOG_DIR:-/var/logs}/identity:/app/logs
    networks:
      - src_srcp_demo_service_net

  hlservice.gateway:
    image: hlservice/gateway:${TAG:-latest}
    build:
      context: ../..
      dockerfile: src/GateWay/Hl.Gateway.WebApi/Dockerfile
      args:
        sln_name: sln/Surging.HlWithIdentity.sln
        host_workdir: src/GateWay/Hl.Gateway.WebApi
        host_name: Hl.Gateway.WebApi.dll
    volumes:
      - ${LOG_DIR:-/var/logs}/gateway:/app/logs
    networks:
      - src_srcp_demo_service_net
networks:
  src_srcp_demo_service_net: 
    external:
      name: hl_surging_service_net