version: '3.7'

services: 
  hlservice.customer:
    environment:
      LogConfigPath: /app/configs/log4net.config
    volumes:
      - ../../src/Shares/Configs:/app/configs

  hlservice.identity:
    environment:
      LogConfigPath: /app/configs/log4net.config
    volumes:
      - ../../src/Shares/Configs:/app/configs

  hlservice.order:
    environment:
      LogConfigPath: /app/configs/log4net.config
    volumes:
      - ../../src/Shares/Configs:/app/configs

  hlservice.product:
    environment:
      LogConfigPath: /app/configs/log4net.config
    volumes:
      - ../../src/Shares/Configs:/app/configs

  hlservice.schedule:
    environment:
      LogConfigPath: /app/configs/log4net.config
    volumes:
      - ../../src/Shares/Configs:/app/configs

  hlservice.stock:
    environment:
      LogConfigPath: /app/configs/log4net.config
    volumes:
      - ../../src/Shares/Configs:/app/configs

  hlservice.organization:
    environment:
      LogConfigPath: /app/configs/log4net.config
    volumes:
      - ../../src/Shares/Configs:/app/configs

  hlservice.basicdata:
    environment:
      LogConfigPath: /app/configs/log4net.config
    volumes:
      - ../../src/Shares/Configs:/app/configs
  hlservice.wsserver:
    environment:
      LogConfigPath: /app/configs/log4net.config
    volumes:
      - ../../src/Shares/Configs:/app/configs
