version: '3.7'

services: 
  hlservice.customer:
    image: hlservice/customer:${TAG:-latest}
    build:
      context: ../..
      dockerfile: src/Servers/Customer/Hl.Customer.ServerHost/Dockerfile
      args:
        host_workdir: src/Servers/Customer/Hl.Customer.ServerHost
        host_name: Hl.Customer.ServerHost.dll
        sln_name: sln/Surging.Hl.sln
    volumes:
      - ${LOG_DIR:-/var/logs}/customer:/app/logs
    networks:
      - src_srcp_demo_service_net

  hlservice.identity:
    image: hlservice/identity:${TAG:-latest}
    build:
      context: ../..
      dockerfile: src/Servers/Identity/Hl.Identity.ServerHost/Dockerfile
      args:
        host_workdir: src/Servers/Identity/Hl.Identity.ServerHost
        host_name: Hl.Identity.ServerHost.dll
        sln_name: sln/Surging.Hl.sln
    volumes:
      - ${LOG_DIR:-/var/logs}/identity:/app/logs
    networks:
      - src_srcp_demo_service_net

  hlservice.order:
    image: hlservice/order:${TAG:-latest}
    build:
      context: ../..
      dockerfile: src/Servers/Order/Hl.Order.ServerHost/Dockerfile
      args:
        host_workdir: src/Servers/Order/Hl.Order.ServerHost
        host_name: Hl.Order.ServerHost.dll
        sln_name: sln/Surging.Hl.sln
    volumes:
      - ${LOG_DIR:-/var/logs}/order:/app/logs
    networks:
      - src_srcp_demo_service_net

  hlservice.product:
    image: hlservice/product:${TAG:-latest}
    build:
      context: ../..
      dockerfile: src/Servers/Product/Hl.Product.ServerHost/Dockerfile
      args:
        host_workdir: src/Servers/Product/Hl.Product.ServerHost
        host_name: Hl.Product.ServerHost.dll
        sln_name: sln/Surging.Hl.sln
    volumes:
      - ${LOG_DIR:-/var/logs}/product:/app/logs
    networks:
      - src_srcp_demo_service_net

  hlservice.schedule:
    image: hlservice/schedule:${TAG:-latest}
    build:
      context: ../..
      dockerfile: src/Servers/Schedule/Hl.Schedule.ServerHost/Dockerfile
      args:
        host_workdir: src/Servers/Schedule/Hl.Schedule.ServerHost
        host_name: Hl.Schedule.ServerHost.dll
        sln_name: sln/Surging.Hl.sln
    volumes:
      - ${LOG_DIR:-/var/logs}/schedule:/app/logs
    networks:
      - src_srcp_demo_service_net

  hlservice.stock:
    image: hlservice/stock:${TAG:-latest}
    build:
      context: ../..
      dockerfile: src/Servers/Stock/Hl.Stock.ServerHost/Dockerfile
      args:
        host_workdir: src/Servers/Stock/Hl.Stock.ServerHost
        host_name: Hl.Stock.ServerHost.dll
        sln_name: sln/Surging.Hl.sln
    volumes:
      - ${LOG_DIR:-/var/logs}/stock:/app/logs
    networks:
      - src_srcp_demo_service_net

  hlservice.organization:
    image: hlservice/organization:${TAG:-latest}
    build:
      context: ../..
      dockerfile: src/Servers/Organization/Hl.Organization.ServerHost/Dockerfile
      args:
        host_workdir: src/Servers/Organization/Hl.Organization.ServerHost
        host_name: Hl.Organization.ServerHost.dll
        sln_name: sln/Surging.Hl.sln
    volumes:
      - ${LOG_DIR:-/var/logs}/organization:/app/logs
    networks:
      - src_srcp_demo_service_net

  hlservice.basicdata:
    image: hlservice/basicdata:${TAG:-latest}
    build:
      context: ../..
      dockerfile: src/Servers/BasicData/Hl.BasicData.ServerHost/Dockerfile
      args:
        host_workdir: src/Servers/BasicData/Hl.BasicData.ServerHost
        host_name: Hl.BasicData.ServerHost.dll
        sln_name: sln/Surging.Hl.sln
    volumes:
      - ${LOG_DIR:-/var/logs}/basicdata:/app/logs
    networks:
      - src_srcp_demo_service_net

  hlservice.wsserver:
    image: hlservice/wsserver:${TAG:-latest}
    build:
      context: ../..
      dockerfile: src/Servers/WsServer/Hl.Ws.ServerHost/Dockerfile
      args:
        host_workdir: src/Servers/WsServer/Hl.Ws.ServerHost
        host_name: Hl.Ws.ServerHost.dll
        sln_name: sln/Surging.Hl.sln
    volumes:
      - ${LOG_DIR:-/var/logs}/wsserver:/app/logs
    networks:
      - src_srcp_demo_service_net


networks:
  src_srcp_demo_service_net: 
    external:
      name: hl_surging_service_net