apiVersion: v1
kind: ConfigMap
metadata:
  name: hlcfg
  namespace: hl
  labels:
    app: hl  
data:
  all__Consul_Register_Conn: consul:8500
  all__Register_SessionTimeout: "50"
  all__Normal_Service_Engine: DotNettyModule;Log4netModule;ConsulModule;EventBusRabbitMQModule;CachingModule;AutoMapperModule;KestrelHttpModule;
  all__Ws_Service_Engine: DotNettyModule;Log4netModule;ConsulModule;EventBusRabbitMQModule;CachingModule;WSProtocolModule;AutoMapperModule;
  all__Schedul_Service_Engine: DotNettyModule;Log4netModule;ConsulModule;EventBusRabbitMQModule;CachingModule;ScheduleModule;AutoMapperModule;KestrelHttpModule;
  all__EventBusConnection: rabbitmq
  all__EventBusUserName: rabbitmq
  all__EventBusPassword: rabbitmq
  all__EventBusPort: "5672"
  all__Environment: Development
  all__ForceDisplayStackTrace: "True"