apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: identity
  namespace: hl
spec:
  paused: true
  template:
    metadata:
      labels:
        app: hl
        component: identity
    spec:
      containers:
      - name: identity
        image: liuhl/identity:v0.0.1
        imagePullPolicy: Always
        env:
        - name: Register_Conn
          valueFrom:
            configMapKeyRef:
              name: hlcfg
              key: all__Consul_Register_Conn
        - name: Register_SessionTimeout
          valueFrom:
            configMapKeyRef:
              name: hlcfg
              key: all__Register_SessionTimeout
        - name: UseEngineParts
          valueFrom:
            configMapKeyRef:
              name: hlcfg
              key: all__Normal_Service_Engine
        - name: EventBusConnection
          valueFrom:
            configMapKeyRef:
              name: hlcfg
              key: all__EventBusConnection
        - name: EventBusUserName
          valueFrom:
            configMapKeyRef:
              name: hlcfg
              key: all__EventBusUserName
        - name: EventBusPassword
          valueFrom:
            configMapKeyRef:
              name: hlcfg
              key: all__EventBusPassword
        - name: EventBusPort
          valueFrom:
            configMapKeyRef:
              name: hlcfg
              key: all__EventBusPort
        - name: Environment
          valueFrom:
            configMapKeyRef:
              name: hlcfg
              key: all__Environment
        - name: ForceDisplayStackTrace
          valueFrom:
            configMapKeyRef:
              name: hlcfg
              key: all__ForceDisplayStackTrace
        - name: SwaggerTitle
          value: "身份认证微服务组件"
        - name: SwaggerDes
          value: "微服务集群身份认证与授权组件"
        ports:
        - containerPort: 8080
          name: http-port
        - containerPort: 100
          name: rpc-port